metadata.format.version = "1.1"

[versions]

# CompileOnly dependencies
velocity = "3.4.0-SNAPSHOT"
# Gradle Plugins
blossom = "2.2.0"
shadow = "9.3.1"
runvelocity = "3.0.2"

netty = "4.2.9.Final"


[libraries]

# Compile Only Dependencies
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
velocity-proxy = { group = "com.velocitypowered", name = "velocity-proxy", version.ref = "velocity" }
netty = { module = "io.netty:netty-all", version.ref = "netty" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.4" }
